---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  bundle:
    parameters:
      ruby_version:
        type: string
        default: 2.6.3
      bundler_version:
        type: string
        default: 1.17.3
      rails_version:
        type: string
        default: '5.2.3'
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - samvera/cached_checkout
      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*
  test:
    parameters:
      ruby_version:
        type: string
        default: 2.6.3
      bundler_version:
        type: string
        default: 1.17.3
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      WAIT_FOR_JEKYLL: 10
    steps:
      - attach_workspace:
          at: ~/
      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
      - samvera/parallel_rspec

workflows:
  version: 2
  ci:
    jobs:
      - bundle:
          name: "bundle_ruby2-6_rails5-2"
          ruby_version: "2.6.3"
          rails_version: "5.2.3"
      - test:
          name: "ruby2-6_rails5-2"
          ruby_version: "2.6.3"
          requires:
            - bundle_ruby2-6_rails5-2
      - bundle:
          name: "bundle_ruby2-5_rails5-2"
          ruby_version: "2.5.5"
          rails_version: "5.2.3"
      - test:
          name: "ruby2-5_rails5-2"
          ruby_version: "2.5.5"
          requires:
            - bundle_ruby2-5_rails5-2
      - bundle:
          name: "bundle_ruby2-4_rails5-2"
          ruby_version: "2.4.6"
          rails_version: "5.2.3"
      - test:
          name: "ruby2-4_rails5-2"
          ruby_version: "2.4.6"
          requires:
            - bundle_ruby2-4_rails5-2
      - bundle:
          name: "bundle_ruby2-6_rails5-1"
          ruby_version: "2.6.3"
          rails_version: "5.1.7"
      - test:
          name: "ruby2-6_rails5-1"
          ruby_version: "2.6.3"
          requires:
            - bundle_ruby2-6_rails5-1
      - bundle:
          name: "bundle_ruby2-5_rails5-1"
          ruby_version: "2.5.5"
          rails_version: "5.1.7"
      - test:
          name: "ruby2-5_rails5-1"
          ruby_version: "2.5.5"
          requires:
            - bundle_ruby2-5_rails5-1
      - bundle:
          name: "bundle_ruby2-4_rails5-1"
          ruby_version: "2.4.6"
          rails_version: "5.1.7"
      - test:
          name: "ruby2-4_rails5-1"
          ruby_version: "2.4.6"
          requires:
            - bundle_ruby2-4_rails5-1
      - bundle:
          name: "bundle_ruby2-6_rails4-2"
          ruby_version: "2.6.3"
          rails_version: "4.2.10"
      - test:
          name: "ruby2-6_rails4-2"
          ruby_version: "2.6.3"
          requires:
            - bundle_ruby2-6_rails4-2
      - bundle:
          name: "bundle_ruby2-5_rails4-2"
          ruby_version: "2.5.5"
          rails_version: "4.2.10"
      - test:
          name: "ruby2-5_rails4-2"
          ruby_version: "2.5.5"
          requires:
            - bundle_ruby2-5_rails4-2
      - bundle:
          name: "bundle_ruby2-4_rails4-2"
          ruby_version: "2.4.6"
          rails_version: "4.2.10"
      - test:
          name: "ruby2-4_rails4-2"
          ruby_version: "2.4.6"
          requires:
            - bundle_ruby2-4_rails4-2

